apiVersion: v1
kind: Service
metadata:
  name: neo4j-db
spec:
  ports:
  - name: browser
    port: 7474
    protocol: TCP
  - name: blot
    port: 7687
    protocol: TCP
  selector:
    app: neo4j-db
  type: NodePort
