apiVersion: v1
kind: Service
metadata:
  name: neo4j-service
spec:
  ports:
  - port: 31001
    name: browser
    targetPort: neo4j-port
    protocol: TCP
  - port: 31002
    name: blot
    targetPort: bolt-port
    protocol: TCP

  selector:
    app: neo4j-app
  type: NodePort
