apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: neo4j-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: neo4j-app
    spec:
      containers:
      - name: noe4j-demo
        image: neo4j
        ports:
        - name: neo4j-port
          containerPort: 7474
        - name: bolt-port
          containerPort: 7687
        volumeMounts:
        - mountPath: /data
          name: myvolume
      volumes:
      - name: myvolume
        awsElasticBlockStore:
          volumeID: vol-04f4e4225f5c52903
