apiVersion: v1
kind: Service
metadata:
  name: k8s-kclproject-site-new
spec:
  ports:
  - name: http
    port: 80
    targetPort: neo4j
    protocol: TCP
  - name: https
    port: 443
    targetPort: neo4j
    protocol: TCP
  selector:
    app: kcl-project
  type: LoadBalancer
