apiVersion: v1
kind: ReplicationController
metadata:
  name: neo4j-db
spec:
  replicas: 1
  selector:
    app: neo4j-db
  template:
    metadata:
      name: neo4j-db
      labels:
        app: neo4j-db
    spec:
      containers:
      - name: neo4j-db
        image: neo4j
        args:
          - "--ignore-db-dir=lost+found"
        ports:
        - name: neo4j-port
          containerPort: 7474
        - name: bolt-port
          containerPort: 7687
        volumeMounts:
        - mountPath: /data
          name: neo4j-storage
      volumes:
        - name: neo4j-storage
          persistentVolumeClaim:
            claimName: db-storage