apiVersion: v1
kind: Service
metadata:
  name: neo4j-app
spec:
  ports:
  - port: 7474
    name: browser
    targetPort: neo4j-port
    protocol: TCP
  - port: 7687
    name: blot
    targetPort: bolt-port
    protocol: TCP
  selector:
    app: neo4j-app
  type: LoadBalancer
