apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: neo4j-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: neo4j-app
    spec:
      containers:
      - name: neo4j-app
        image: neo4j
        ports:
        - name: neo4j-port
          containerPort: 7474
        - name: bolt-port
          containerPort: 7687
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
      - name: data
        nfs:
          server: us-east-1a.fs-b750c0fe.efs.us-east-1.amazonaws.com
          path: /
