kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gdb-storage
  annotations:
    volume.beta.kubernetes.io/storage-class: "neo4j.standard"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
