kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: neo4j-storage
  annotations:
    volume.beta.kubernetes.io/storage-class: "standard_1"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
