apiVersion: v1
kind: Pod
metadata:
  name: neo4j-k8s
  labels:
        app: neo4j-app

spec:
   containers:
      - name: neo4j-demo
        image: neo4j
        ports:
        - name: neo4j-port
          containerPort: 7474
        - name: bolt-port
          containerPort: 7687
