apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: neo4j
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: neo4j-demo
    spec:
      containers:
      - name: neo4j-app
        image: neo4j
        env:
          - name: NEO4J_dbms_read__only
            value: true
        ports:
        - name: neo4j-port
          containerPort: 7474
        - name: bolt-port
          containerPort: 7687
        volumeMounts:
        - mountPath: /data
          name: neo4j
      volumes:
      - name: neo4j
          persistentVolumeClaim:
          claimName: myclaim
